controllerManager:
  manager:
    image:
      repository: harbor.cscsqa.chorus-tre.ch/chorus/workbench-operator
    args:
      - --leader-elect
      - --registry=harbor.cscsqa.chorus-tre.ch
      - --xpra-server-image=harbor.cscsqa.chorus-tre.ch/apps/xpra-server
      - --apps-repository=apps
      - --socat-image=alpine/socat:1.8.0.0
      - --metrics-bind-address=:8080

imagePullSecrets:
  - name: regcred
