environments:
  - name: chorus-build
    description: CHORUS build
    envRepoURL: https://github.com/CHORUS-TRE/environment-template.git
    registryURL: harbor.build-t.chorus-tre.ch
    cluster: in-cluster

  - name: chorus
    description: CHORUS
    envRepoURL: https://github.com/CHORUS-TRE/environment-template.git
    registryURL: harbor.build-t.chorus-tre.ch
    cluster: chorus