environments:
  - name: chorus-build
    description: CHORUS build
    envRepoURL: https://github.com/CHORUS-TRE/environment-template.git
    envRepoRevision: feat/helm-chart-install
    registryURL: harbor.build-t.chorus-tre.ch
    cluster: in-cluster
