environments:
  - name: chorus-build
    description: CHORUS build
    envRepoURL: https://github.com/CHORUS-TRE/environment-template.git
    registryURL: harbor.build.chorus-tre.ch
    cluster: in-cluster
