valkey:
  auth:
    enabled: true
    sentinel:
      enabled: false
    existingSecret: oauth2-proxy-cache-secret
    existingSecretPasswordKey: REDIS_PASSWORD

  primary:
    resourcesPreset: "small"

  metrics:
    resourcesPreset: "micro"
