controllerManager:
  manager:
    image:
      repository: harbor.192.168.120.181.nip.io/chorus/workbench-operator
    args:
      - --leader-elect
      - --registry=harbor.192.168.120.181.nip.io
      - --xpra-server-image=harbor.192.168.120.181.nip.io/apps/xpra-server
      - --apps-repository=apps
      - --socat-image=alpine/socat:1.8.0.0
      - --metrics-bind-address=:8080
imagePullSecrets:
  - name: regcred
