ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: i2b2.qa.chorus-tre.ch 
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: i2b2-tls
      hosts:
        - i2b2.qa.chorus-tre.ch
cm:
  urlCellPM: "http://chorus-qa-i2b2-wildfly:8080/i2b2/services/PMService/"
  pmURL: "http://chorus-qa-i2b2-wildfly:8080/i2b2/rest/PMService/getServices"
  whiteListURL: "http://chorus-qa-i2b2-wildfly:8080"
  ProxyPass: "http://chorus-qa-i2b2-wildfly:8080/i2b2/"
