env:
  url: "https://didata.192.168.120.181.nip.io"
ingress:
  hosts:
    - host: didata.192.168.120.181.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: didata-tls
      hosts:
        - didata.192.168.120.181.nip.io
