env:
  url: "https://didata.chorus-tre.ch"

ingress:
  hosts:
    - host: didata.chorus-tre.ch
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: didata-tls
      hosts:
        - didata.chorus-tre.ch

