matomo:
  matomoWebsiteName: chorus-cscsqa
  matomoWebsiteHost: https://matomo.cscsqa.chorus-tre.ch
  resourcesPreset: "large"
  ingress:
    hostname: "makoto.cscsqa.chorus-tre.ch"
  externalDatabase:
    host: "chorus-cscsqa-matomo-db"

  # temp fix for https://github.com/bitnami/charts/issues/29884
  pdb:
    create: false
  podLabels:
    app.kubernetes.io/component: matomo
  extraDeploy:
    - apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: chorus-cscsqa-matomo
        namespace: matomo
      spec:
        maxUnavailable: 1
        selector:
          matchLabels:
            app.kubernetes.io/component: matomo
