ingress:
  hosts:
    - host: wildfly.cscsqa.chorus-tre.ch
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wildfly.cscsqa.chorus-tre.ch-tls
      hosts:
        - wildfly.cscsqa.chorus-tre.ch
env:
  DS_TYPE: "postgres"
  DS_IP: "chorus-cscsqa-i2b2-db"
  DS_PORT: "5432"
  DS_PM_USER: "i2b2pm"
  DS_WB_USER: "i2b2workdata"
  DS_HIVE_USER: "i2b2hive"
  DS_PM_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_pm_pass
  DS_WD_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_wd_pass
  DS_HIVE_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_hive_pass
  DS_CRC_IP: "chorus-cscsqa-i2b2-db"
  DS_CRC_PORT: "5432"
  DS_CRC_USER: "i2b2demodata"
  DS_CRC_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_crc_pass
  DS_CRC_DB: "i2b2demodata"
  DS_ONT_IP: "chorus-cscsqa-i2b2-db"
  DS_ONT_PORT: "5432"
  DS_ONT_USER: "i2b2metadata"
  DS_ONT_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_ont_pass
  DS_ONT_DB: "i2b2metadata"
