oauth2-proxy:
  config:
    # keys needed:
    # - cookie-secret (openssl rand -base64 32 | head -c 32 | base64)
    # - client-secret (from Keycloak)
    # - client-id
    existingSecret: alertmanager-oauth2-proxy-oidc-secret

    # See: https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak_oidc/
    configFile: |-
      email_domains = [ "chuv.ch" ]
      redirect_url = "https://alertmanager.build-t.chorus-tre.ch/oauth2/callback"
      oidc_issuer_url = "https://auth.build-t.chorus-tre.ch/realms/infra"
      scope = "openid email"
      provider = "keycloak-oidc"
      provider_display_name = "Keycloak"

  sessionStorage:
    type: redis
    redis:
      existingSecret: alertmanager-oauth2-proxy-secret
      passwordKey: REDIS_PASSWORD
      standalone:
        connectionUrl: redis://chorus-build-t-oauth2-proxy-valkey-primary.keycloak.svc.cluster.local:6379/1

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    path: /oauth2
    hosts:
      - alertmanager.build-t.chorus-tre.ch
    tls:
      - secretName: alertmanager-general-tls
        hosts:
          - alertmanager.build-t.chorus-tre.ch
