ingress:
  hosts:
    - host: wildfly.chorus-tre.ch
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wildfly.chorus-tre.ch-tls
      hosts:
        - wildfly.chorus-tre.ch

env:
  PG_PASS:
    existingSecret: i2b2-wildfly-secret
    key: pg_pass
  DS_TYPE: "postgres"
  DS_PASSWORD:
    existingSecret: i2b2-wildfly-secret
    key: ds_password
  DS_WD_USER: "i2b2workdata"
  DS_WD_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_wd_pass
  DS_WD_IP: "chorus-i2b2-db"
  DS_WD_PORT: "5432"
  DS_WD_DB: "i2b2"
  DS_WD_SCHEMA: "i2b2workdata"
  DS_CRC_IP: "chorus-i2b2-db"
  DS_CRC_USER: "i2b2"
  DS_CRC_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_crc_pass
  DS_CRC_PORT: "5432"
  DS_CRC_DB: "i2b2"
  DS_CRC_SCHEMA: "i2b2demodata"
  DS_CRC_DB_TYPE: "pg"
  DS_ONT_IP: "chorus-i2b2-db"
  DS_ONT_USER: "i2b2"
  DS_ONT_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_ont_pass
  DS_ONT_PORT: "5432"
  DS_ONT_DB: "i2b2"
  DS_ONT_SCHEMA: "i2b2metadata"
  DS_ONT_DB_TYPE : "pg"
  DS_PM_DB: "i2b2"
  DS_PM_SCHEMA: "i2b2pm"
  DS_PM_PORT: "5432"
  DS_PM_IP: "chorus-i2b2-db"
  DS_PM_USER: "i2b2"
  DS_PM_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_pm_pass
  DS_PM_DB_TYPE: "pg"
  DS_HIVE_IP: "chorus-i2b2-db"
  DS_HIVE_USER: "i2b2"
  DS_HIVE_PASS:
    existingSecret: i2b2-wildfly-secret
    key: ds_hive_pass
  DS_HIVE_PORT: "5432"
  DS_HIVE_DB: "i2b2"
  DS_HIVE_SCHEMA: "i2b2hive"
  DS_HIVE_DB_TYPE : "pg"
  DS_CSV_DELIMITER: ","
  DS_BCP_DELIMITER: "^"
