matomo:
  matomoWebsiteName: chorus
  matomoWebsiteHost: https://makoto.chorus-tre.ch
  resourcesPreset: "large"
  existingSecret: "matomo-secret"
  ingress:
    hostname: "makoto.chorus-tre.ch"
  externalDatabase:
    host: "chorus-matomo-db"
    existingSecret: "matomo-db-secret"
  # temp fix for https://github.com/bitnami/charts/issues/29884
  pdb:
    create: false
  podLabels:
    app.kubernetes.io/component: matomo
  extraDeploy:
    - apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: chorus-matomo
        namespace: matomo
      spec:
        maxUnavailable: 1
        selector:
          matchLabels:
            app.kubernetes.io/component: matomo
