matomo:
  matomoWebsiteName: chorus
  matomoWebsiteHost: https://makoto.192.168.120.181.nip.io
  resourcesPreset: "small"
  existingSecret: "matomo-secret"
  ingress:
    hostname: "makoto.192.168.120.181.nip.io"
  externalDatabase:
    host: "chorus-matomo-db"
    existingSecret: "matomo-db-secret"
  # temp fix for https://github.com/bitnami/charts/issues/29884
  pdb:
    create: false
  podLabels:
    app.kubernetes.io/component: matomo
  extraDeploy:
    - apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: chorus-matomo
        namespace: matomo
      spec:
        maxUnavailable: 1
        selector:
          matchLabels:
            app.kubernetes.io/component: matomo
