sensor:
  registry: harbor.build.chorus-tre.ch
  dockerConfig:
    secretName: harbor-dockerconfigjson-secret

serviceAccount:
  name: argo-ci-sa

# Creates the webhook and matching events on the GibHub EventSource.
webhookEvents:
  - name: ci
    repositories:
      - owner: chorus-tre
        names:
          - images

    # That secret must contain the following keys:
    # - token (a GitHub pat), and secret (the webhook secret).
    secretName: argo-ci-github-images

  - name: chorus-web-ui
    repositories:
      - owner: chorus-tre
        names:
          - chorus-web-ui
    secretName: argo-ci-github-chorus-web-ui

  - name: chorus-backend
    repositories:
      - owner: chorus-tre
        names:
          - chorus-backend
    secretName: argo-ci-github-chorus-backend

  - name: workbench-operator
    repositories:
      - owner: chorus-tre
        names:
          - workbench-operator
    secretName: argo-ci-github-workbench-operator

ingress:
  hosts:
    - host: webhook.build.chorus-tre.ch
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - webhook.build.chorus-tre.ch
      secretName: argo-ci-tls
