valkey:
  auth:
    enabled: true
    sentinel:
      enabled: false
    existingSecret: argo-cd-cache-secret
    # That's the key wanted by argo-cd.
    existingSecretPasswordKey: redis-password
  primary:
    resourcesPreset: "small"

  metrics:
    resourcesPreset: "micro"
